version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3.11-management"
    hostname: "rabbitmq"
    container_name: "rabbitmq-container"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq:/var/lib/rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "qwerty123"
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: "30s"
      timeout: "30s"
      retries: 3

  images-db:
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
      POSTGRES_DB: "images"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./.postgres/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    container_name: "images-db-container"
    healthcheck:
      test: "pg_isready -U postgres -d images"
      interval: "10s"
      timeout: "10s"
      retries: 3

  sample-producer:
    build: "./producer-service"
    image: "sample-producer:1.0"
    depends_on:
      rabbitmq:
        condition: "service_healthy"
      images-db:
        condition: "service_healthy"
    volumes:
      - "./uploads:/app/uploads"
    ports:
      - "${PORT:-3000}:3000"
    network_mode: "host"
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
      POSTGRES_DB_NAME: "images"
      POSTGRES_DB_HOST: "localhost"
      POSTGRES_DB_PORT: "5432"

      MESSAGE_BROKER_USER: "admin"
      MESSAGE_BROKER_PASSWORD: "qwerty123"
      MESSAGE_BROKER_HOST: "localhost"
      MESSAGE_BROKER_PORT: "5672"

      LOCAL_IMAGES_DIR: "uploads"
    container_name: "sample-producer-container"

  sample-consumer:
    build: "./consumer-service"
    image: "sample-consumer:1.0"
    depends_on:
      rabbitmq:
        condition: "service_healthy"
      images-db:
        condition: "service_healthy"
    volumes:
      - "./uploads:/app/uploads"
    network_mode: "host"
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
      POSTGRES_DB_NAME: "images"
      POSTGRES_DB_HOST: "localhost"
      POSTGRES_DB_PORT: "5432"

      MESSAGE_BROKER_USER: "admin"
      MESSAGE_BROKER_PASSWORD: "qwerty123"
      MESSAGE_BROKER_HOST: "localhost"
      MESSAGE_BROKER_PORT: "5672"

      LOCAL_IMAGES_DIR: "uploads"
    container_name: "sample-consumer-container"
